### PR TITLE
Context titles are automatically titlecased

### PR DESCRIPTION
**Pull request by aaronjensen**
@sbellware suggested this. It's too hard to remember all the title case rules, so this does it automatically for us. I did have to switch to using bundler because activesupport doesn't install properly without it.

### CODE REVIEW

**Comment by ntl** [comment]
Hi @aaronjensen . I'd love to merge your PR but unfortunately life circumstances have forced me to find a new owner for TestBench. Are you interested in taking on that role, by chance?

**Comment by aaronjensen** [comment]
🤣

**Comment by mbriggs** [comment]
+1

**Comment by sbellware** [comment]
Omg, this is brilliant 🤣. Started my day with a laugh!

**Pull request closed without merging**
